### PR TITLE
feat(DevTools): add all options to configure the Redux DevTools communication

### PR DESCRIPTION
**Pull request by dannyBies**
Further work based on https://github.com/aurelia/store/pull/52

I added all available options based on https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/index.d.ts

Note:
The options actionsBlacklist and actionsWhitelist are of type string | string[]; I noticed that both types would result in errors when passed to the Redux Devtools. To fix string[] I have changed the call to send data to Redux DevTools to include an object with a type property instead of a string (https://github.com/zalmoxisus/redux-devtools-extension/blob/5f4dd812c58abd4567b01d453f9b4e879d707dcc/docs/API/Methods.md#send)
This makes the string[] work but not the string type. I could not find a solution to fix this so I removed this type from the DevToolsOptions interface. 

If anyone has any idea on how to fix this I would gladly implement it.

A bit too late for the 1.0.0 release 🎉

### CODE REVIEW

**Comment by zewa666** [comment]
Good idea. So first can we extract the type of DevToolsOptions to another file? Store.ts is getting a bit messy. I'd recommend something like `devtools.ts`.

And second, I see that you've added the new Action interface, but what I don't get is why you've changed name to type. Any particular reason for that? Anyways I feel like this PR has too many responsibilities so maybe we could split the two things up after clarifying the type<->name change.

**Comment by dannyBies** [comment]
When we connect to the extension and pass in our options and create the [send() method](https://github.com/zalmoxisus/redux-devtools-extension/blob/0f5bac0c9a762cfd8c53e7938cb6967e2e15e1de/src/app/api/index.js#L204)
We do a call to [isFiltered()](https://github.com/zalmoxisus/redux-devtools-extension/blob/0f5bac0c9a762cfd8c53e7938cb6967e2e15e1de/src/app/api/filters.js#L19) in which we expect action.type to be defined. In our case we used action.name instead of action.type, so now we use the [correct type](https://github.com/reduxjs/redux/blob/master/index.d.ts#L19). 

I made the change from type <-> name to get all the DevTool options working so I think it belongs in the scope of this PR.

**Comment by zewa666** [comment]
ahh ok, now I see what this is about. So actually the DevTools need the property to be called type. Hmm I was wondering whether this could introduce breaking changes. But it seems the only place I could [think of](https://github.com/aurelia/store/blob/master/src/store.ts#L167) is already mapping that to the name property. So now instead of sending the actions name as string you could send the whole action. I see.

When I started this plugin I didn't think of that Redux uses type as their describer, so name was a valid choice in my case. Guess since the property `name` was used only internally though, it shouldn't matter to rename it.

**Comment by zewa666** [comment]
Ok so I'd still ask you to move the three interfaces `Action`, `ActionCreator` and `DevToolsOptions` into `devtools.ts` just to clean store.ts up. But otherwise this looks good for me.

Also please make sure to do the barrel export from `aurelia-store.ts` for the moved interfaces.

**Comment by dannyBies** [comment]
Done, thanks for reviewing!

**Comment by zewa666** [comment]
As last time great work and thanks for the contribution @dannyBies

**Pull request merged**
