### PR TITLE
Narrow dependency importing to improve commonjs bundling

### PR DESCRIPTION
**Pull request by timfish**
A couple of the JavaScript contexts in Electron have to use commonjs which can't be tree shaken. This means simply importing `Store` gives you a base bundle of 360KB. 

After these changes, it's down to 150KB as `reflect-metadata` now isn't required either.

### CODE REVIEW

**Comment by zewa666** [comment]
Have taken a look where the rest is coming from? 150kb is still quite a lot.

**Comment by timfish** [comment]
RxJs is just under 120k of that. 

image

I think they removed the submodule imports from RxJs v6.

**Comment by timfish** [comment]
Actually, I think this might work but it'll need more testing with webpack:
```
import { Observable } from "rxjs/internal/Observable";
import { BehaviorSubject } from "rxjs/internal/BehaviorSubject";
```

**Comment by timfish** [comment]
The above helped a bit, but the main culprit is the top level export of `test-helpers` which brings in all the operators.
```
export * from "./test-helpers"
```
Commenting that out and the bundle is down to 45k:

image

The Rxjs type definitions seem to suggest that you can import the individual operators using `rxjs-compat` but I don't think we should take a dependency on that. 

Would moving `test-helpers` out from the top level export be a semver major change?

**Comment by zewa666** [comment]
I thought that Rx is the issue. Sadly the new way of v6 is very bad compared to v5 where patched imports allowed much better optimizations. Found some hints here in a link about path definitions https://chat.stackoverflow.com/rooms/172455/discussion-on-question-by-royi-namir-rxjs-v6-loads-many-unnecessary-modules. I'm just not very good with Webpack.

Anyways with regards to test-helpers doesnt changing its imports to internal reduce the size as well? Excluding them from the barrel export would be a breaking change

**Comment by zewa666** [comment]
Here is the link i've been searching for https://github.com/ReactiveX/rxjs/blob/d231053616ab4e5d2541818314110df626e6bf5a/doc/pipeable-operators.md#build-and-treeshaking

**Comment by zewa666** [comment]
Also you shouldnt import from internal, as the name suggests, as those are likely to be changed.

**Comment by zewa666** [comment]
Also maybe give the last comment here a look. https://github.com/angular/angular-cli/issues/9069

Really i think the trouble is more about the bundler, specifically webpack, than the Store plugin itself.

**Comment by timfish** [comment]
Thanks for the helpful links. It does looks like the Rxjs issue is webpack related.

I've reverted the changes to only the Aurelia references which simply stops `aureila-teamplating` and `aurelia-binding` from being included.

**Comment by timfish** [comment]
I agree that we shouldn't spend too much time on ES5 + CommonJs bundling output.

In Electron where no network is involved, a 150k bundle size is perfectly acceptable.

**Comment by zewa666** [comment]
thx for the help @timfish

**Pull request merged**
