### PR TITLE
add-operators

### PR DESCRIPTION
**Pull request by alexisargyris**

### CODE REVIEW

**Comment by zewa666** [comment]
Adding the file operators would bundle all operators at once. This will lead to larger package sizes. We should mention how one can load those individually. Thanks for the first steps though.

**Comment by alexisargyris** [comment]
Very true! So the user should start out by installing aurelia-store either through either `npm install aurelia-store` or `au install aurelia-store`.

Then the user should edit aurelia.json in order to configure aurelia-store, rxjs and rxjs/operators. This may be done either manually or through `au import aurelia-store`. In the latter case the correct entries will be added for aurelia-store and rxjs but _all_ rxjs/operators will be loaded (leading to larger package sizes), so the user needs to edit the rxjs/operators entry manually and only load the operators of interest.

Is this correct?

**Comment by zewa666** [comment]
Correct. I also think the import instructions for the Plugin are still rxjs5 based, so these need an update as well. Ill be back beginning of July and tackle all the things.

**Comment by zewa666** [comment]
Thanks for your initial work. I've merged and fixed a few other things. Should be available in the live docs soon

**Pull request merged**
