### PR TITLE
Bump ts rxjs

### PR DESCRIPTION
**Pull request by zewa666**

### CODE REVIEW

**Comment by dbishop-kcura** [comment]
@zewa666 Wondering if there is any planned timeframe for when this 2.0.0 version may be merged and released?

**Comment by zewa666** [comment]
@bigopon can you take a look at the PR and do a release?

**Comment by dbishop-kcura** [comment]
@zewa666 @bigopon @Vheissu Any timetable for when we think this PR can be reviewed and merged? Interested in consuming 2.0.0 when it is released.

**Comment by bigopon** [comment]
It's been released. My bad that it's been delayed quite a bit.

**Pull request merged**
