### PR TITLE
chore(build): enable UMD build for use in conjunction with aurelia-script

### PR DESCRIPTION
**Pull request by bigopon**
@zewa666 I don't know what the namespace of rxjs would be when used in UMD format, please change it if needed (i made it global.rxjs === window.rxjs);

cc @EisenbergEffect

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Seems fine to me. @zewa666 Ok to merge this one?

**Comment by zewa666** [comment]
@bigopon I think this is ok. `window.rxse` is the new default global export as of RxJS v6 earlier it used to be `window.Rx`. Do I get it right that this build does not include RxJS but the user has to do a custom script reference for a cdn host? If so that is great because we don't clutter our bundle.

Great work, @EisenbergEffect I'd say this is good to merge and release

**Comment by bigopon** [comment]
@zewa666 Cool, so following is how it's going to be for umd build:

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('rxjs'), require('aurelia-dependency-injection'), require('aurelia-logging'), require('aurelia-pal'), require('rxjs/operators')) :
    typeof define === 'function' && define.amd ? define(['exports', 'rxjs', 'aurelia-dependency-injection', 'aurelia-logging', 'aurelia-pal', 'rxjs/operators'], factory) :
    (global = global || self, factory((global.au = global.au || {}, global.au.store = {}),
    global.rxse,
    global.au,
    global.au.LogManager,
    global.au,
    global.rxse));
}(this, function (
  exports,
  rxjs,
  aureliaDependencyInjection,
  aureliaLogging,
  aureliaPal,
  operators) { 'use strict';
  ...
});
```

**Comment by zewa666** [comment]
Shit sry that was a Typo. Rxjs was ok as you had.

**Comment by EisenbergEffect** [comment]
@bigopon is a rock star 🎸

**Pull request merged**
