### PR TITLE
fix(pal): clear only store defined marks and measures

### PR DESCRIPTION
**Pull request by vitar**
Before: on store.dispatch all marks and measures are cleared, including user defined.
After: on store.dispatch only store defined marks and measures are cleared.

No breaking changes

### CODE REVIEW

**Comment by vitar** [comment]
Unrelated error with post-tests routine.
Need help.

**Comment by zewa666** [comment]
@vitar awesome, nice approach. It would be great if you could add just two small unit tests making sure that only appropriate entries are cleared. This would act as contract test to document the Intention.

The circle build is fine, coveralls is not configured for custom branches

**Comment by vitar** [comment]
Improved and added store log duration related unit tests.
Added few middleware log duration related tests, but not sure about scenarios.
Please review.

**Comment by vitar** [comment]
Any comments? More reviewers?

**Comment by zewa666** [comment]
I was just about to complete the merge :)

thanks again for your contribution @vitar

**Pull request merged**
